version: '3'
services:
  app:
    container_name: tigernodeofspace-client
    image: fabriceesope/tigernodeofspace-client
    restart: always
    build: .
    ports:
      - '80:3000'
    depends_on:
      - tigernodesofspace
  tigernodesofspace:
    image: fabriceesope/tigernodesofspace
